<?php

		/**
		 * Generated by the WordPress Option Page generator
		 * at http://jeremyhixon.com/wp-tools/option-page/
		 */

	class matm_google_reivews_settings {
		private $google_reviews_options;

		public function google_reviews_add_plugin_page() {
			add_menu_page(
				'Google Reviews', // page_title
				'Google Reviews', // menu_title
				'manage_options', // capability
				'google-reviews', // menu_slug
				array( $this, 'google_reviews_create_admin_page' ), // function
				'dashicons-admin-generic', // icon_url
				75 // position
			);
		}

		public function google_reviews_create_admin_page() {
			$this->google_reviews_options = get_option( 'matm_google_reviews_options' ); ?>

			<div class="wrap">
				<h2>Google Reviews</h2>
				<p>MATM Google Reviews plugin settings</p>
				<?php settings_errors(); ?>

				<form method="post" action="options.php">
					<?php
						settings_fields( 'google_reviews_option_group' );
						do_settings_sections( 'google-reviews-admin' );
						submit_button();
					?>
				</form>
                <a href="">Get Reviews Now</a>
			</div>
		<?php }

		public function google_reviews_page_init() {
			register_setting(
				'google_reviews_option_group', // option_group
				'matm_google_reviews_options', // option_name
				array( $this, 'google_reviews_sanitize' ) // sanitize_callback
			);

			add_settings_section(
				'google_reviews_setting_section', // id
				'Settings', // title
				array( $this, 'google_reviews_section_info' ), // callback
				'google-reviews-admin' // page
			);

			add_settings_field(
				'google_maps_api_key', // id
				'Google Maps API Key', // title
				array( $this, 'google_maps_api_key_callback' ), // callback
				'google-reviews-admin', // page
				'google_reviews_setting_section' // section
			);

			add_settings_field(
				'google_maps_place_id', // id
				'Google Maps Place ID', // title
				array( $this, 'google_maps_place_id_callback' ), // callback
				'google-reviews-admin', // page
				'google_reviews_setting_section' // section
			);
		}

		public function google_reviews_sanitize($input) {
			$sanitary_values = array();
			if ( isset( $input['google_maps_api_key'] ) ) {
				$sanitary_values['google_maps_api_key'] = sanitize_text_field( $input['google_maps_api_key'] );
			}

			if ( isset( $input['google_maps_place_id'] ) ) {
				$sanitary_values['google_maps_place_id'] = sanitize_text_field( $input['google_maps_place_id'] );
			}

			return $sanitary_values;
		}

		public function google_reviews_section_info() {

		}

		public function google_maps_api_key_callback() {
			printf(
				'<input class="regular-text" type="text" name="matm_google_reviews_options[google_maps_api_key]" id="google_maps_api_key" value="%s">',
				isset( $this->google_reviews_options['google_maps_api_key'] ) ? esc_attr( $this->google_reviews_options['google_maps_api_key']) : ''
			);
		}

		public function google_maps_place_id_callback() {
			printf(
				'<input class="regular-text" type="text" name="matm_google_reviews_options[google_maps_place_id]" id="google_maps_place_id" value="%s">',
				isset( $this->google_reviews_options['google_maps_place_id'] ) ? esc_attr( $this->google_reviews_options['google_maps_place_id']) : ''
			);
		}
	}

	/*
	 * Retrieve this value with:
	 * $google_reviews_options = get_option( 'matm_google_reviews_options' ); // Array of All Options
	 * $google_maps_api_key = $google_reviews_options['google_maps_api_key']; // Google Maps API Key
	 * $google_maps_place_id = $google_reviews_options['google_maps_place_id']; // Google Maps Place ID
	 */

